var data = [
  {
    id: "1",
    name: "Jen",
    city: "Melbourne",
    region: "Turkey",
    education: "Lisans",
    age: "65",
    fake1: "fake",
    fake2: "fake2",
    fake3: "fake3",
    fake4: "fake4",
    fake5: "fake5",
    fake6: "fake6",
    fake7: "fake7",
    fake8: "fake8",
    fake9: "fake9",
    fake10: "fake10",
  },
  {
    id: "2",
    name: "Roger",
    city: "Melbourne",
    region: "Turkey",
    education: "Lisans",
    age: "34",
    fake1: "fake",
    fake2: "fake2",
    fake3: "fake3",
    fake4: "fake4",
    fake5: "fake5",
    fake6: "fake6",
    fake7: "fake7",
    fake8: "fake8",
    fake9: "fake9",
    fake10: "fake10",
  },
  {
    id: "3",
    name: "Rob",
    city: "Sydney",
    region: "Turkey",
    education: "Lisans",
    age: "23",
    fake1: "fake5sdflksdlfksldfsdfsdf",
    fake2: "fakfake5sdflksdlfksldfsdfsdfe2",
    fake3: "fakfake5sdflksdlfksldfsdfsdfe3",
    fake4: "fake5sdflksdlfksldfsdfsdf",
    fake5: "fake5sdflksdlfksldfsdfsdf",
    fake6: "fake6",
    fake7: "fake7",
    fake8: "fake8",
    fake9: "fake9",
    fake10: "fake10",
  },
];

var detailTableData1 = [
  {
    id: "4",
    name: "Jen",
    city: "Melbourne",
    region: "Turkey",
    education: "Lisans",
    age: "5667",
    fake1: "fake",
    fake2: "fake2",
    fake3: "fake3",
    fake4: "fake4",
    fake5: "fake5",
    fake6: "fake6",
    fake7: "fake7",
    fake8: "fake8",
    fake9: "fake9",
    fake10: "fake10",
  },
  {
    id: "5",
    name: "Roger",
    city: "Melbourne",
    region: "Turkey",
    education: "Lisans",
    age: "767",
    fake1: "fake",
    fake2: "fake2",
    fake3: "fake3",
    fake4: "fake4",
    fake5: "fake5",
    fake6: "fake6",
    fake7: "fake7",
    fake8: "fake8",
    fake9: "fake9",
    fake10: "fake10",
  },
];
var detailTableData2 = [
  {
    id: "6",
    name: "Jen",
    city: "Melbourne",
    region: "Turkey",
    education: "Lisans",
    age: "5667",
    fake1: "fake",
    fake2: "fake2",
    fake3: "fake3",
    fake4: "fake4",
    fake5: "fake5",
    fake6: "fake6",
    fake7: "fake7",
    fake8: "fake8",
    fake9: "fake9",
    fake10: "fake10",
  },
  {
    id: "7",
    name: "Roger",
    city: "Melbourne",
    region: "Turkey",
    education: "Lisans",
    age: "767",
    fake1: "fake",
    fake2: "fake2",
    fake3: "fake3",
    fake4: "fake4",
    fake5: "fake5",
    fake6: "fake6",
    fake7: "fake7",
    fake8: "fake8",
    fake9: "fake9",
    fake10: "fake10",
  },
];

var detailTableData3 = [
  {
    id: "8",
    name: "Jen",
    city: "Melbourne",
    region: "Turkey",
    education: "Lisans",
    age: "5667",
    fake1: "fake",
    fake2: "fake2",
    fake3: "fake3",
    fake4: "fake4",
    fake5: "fake5",
    fake6: "fake6",
    fake7: "fake7",
    fake8: "fake8",
    fake9: "fake9",
    fake10: "fake10",
  },
];

var dataDetail = {
  1: detailTableData1,
  2: detailTableData2,
  3: detailTableData3,
};

var modalTableData = [
  {
    id: "1",
    name: "Jen",
    city: "Melbourne",
    region: "Turkey",
    education: "Lisans",
    age: "65",
    fake1: "fake",
    fake2: "rtrt",
    fake3: "gggg",
    fake4: "dddd",
  },
  {
    id: "2",
    name: "AAAA",
    city: "BBBB",
    region: "ZZZZ",
    education: "CCCC",
    age: "98",
    fake1: "FFF",
    fake2: "GGG",
    fake3: "fake3",
    fake4: "fake4",
  },
];

var toDoListData = [
  {
    segment: "2000",
    name: "Dış Yıkama",
    jobCode: "10 SÖK TAK",
    componentCode: "1000- MOTOR",
    startDate: "8.10.2021",
    endDate: "8.10.2021",
  },
];

var workOrderDetailData = [
  {
    column1: "7888",
    column2: "7559099",
    column3: "HS",
    column4: "şanzıman",
    column5: "987987",
    column6: "7.10.2021 00:00:00",
    column7: "Teklif Verildi",
    column8: "7888",
    column9: "7888",
    column10: "7888",
    column11: "7888",
  },
];
