var data = [
    {
      id: "1",
      name: "Jen",
      city: "Melbourne",
      region: "Turkey",
      education: "Lisans",
      age: "65",
      fake1: "fake",
      fake2: "fake2",
      fake3: "fake3",
      fake4: "fake4",
      fake5: "fake5",
      fake6: "fake6",
      fake7: "fake7",
      fake8: "fake8",
      fake9: "fake9",
      fake10: "fake10",
    },
    {
      id: "2",
      name: "Roger",
      city: "Melbourne",
      region: "Turkey",
      education: "Lisans",
      age: "34",
      fake1: "fake",
      fake2: "fake2",
      fake3: "fake3",
      fake4: "fake4",
      fake5: "fake5",
      fake6: "fake6",
      fake7: "fake7",
      fake8: "fake8",
      fake9: "fake9",
      fake10: "fake10",
    },
    {
      id: "3",
      name: "Rob",
      city: "Sydney",
      region: "Turkey",
      education: "Lisans",
      age: "23",
      fake1: "fake5sdflksdlfksldfsdfsdf",
      fake2: "fakfake5sdflksdlfksldfsdfsdfe2",
      fake3: "fakfake5sdflksdlfksldfsdfsdfe3",
      fake4: "fake5sdflksdlfksldfsdfsdf",
      fake5: "fake5sdflksdlfksldfsdfsdf",
      fake6: "fake6",
      fake7: "fake7",
      fake8: "fake8",
      fake9: "fake9",
      fake10: "fake10",
    },
  ];

  var detailTableData1 = [
    {
      id: "4",
      name: "Jen",
      city: "Melbourne",
      region: "Turkey",
      education: "Lisans",
      age: "5667",
      fake1: "fake",
      fake2: "fake2",
      fake3: "fake3",
      fake4: "fake4",
      fake5: "fake5",
      fake6: "fake6",
      fake7: "fake7",
      fake8: "fake8",
      fake9: "fake9",
      fake10: "fake10",
    },
    {
      id: "5",
      name: "Roger",
      city: "Melbourne",
      region: "Turkey",
      education: "Lisans",
      age: "767",
      fake1: "fake",
      fake2: "fake2",
      fake3: "fake3",
      fake4: "fake4",
      fake5: "fake5",
      fake6: "fake6",
      fake7: "fake7",
      fake8: "fake8",
      fake9: "fake9",
      fake10: "fake10",
    },
  ];
  var detailTableData2 = [
    {
      id: "6",
      name: "Jen",
      city: "Melbourne",
      region: "Turkey",
      education: "Lisans",
      age: "5667",
      fake1: "fake",
      fake2: "fake2",
      fake3: "fake3",
      fake4: "fake4",
      fake5: "fake5",
      fake6: "fake6",
      fake7: "fake7",
      fake8: "fake8",
      fake9: "fake9",
      fake10: "fake10",
    },
    {
      id: "7",
      name: "Roger",
      city: "Melbourne",
      region: "Turkey",
      education: "Lisans",
      age: "767",
      fake1: "fake",
      fake2: "fake2",
      fake3: "fake3",
      fake4: "fake4",
      fake5: "fake5",
      fake6: "fake6",
      fake7: "fake7",
      fake8: "fake8",
      fake9: "fake9",
      fake10: "fake10",
    },
  ];

  var detailTableData3 = [
    {
      id: "8",
      name: "Jen",
      city: "Melbourne",
      region: "Turkey",
      education: "Lisans",
      age: "5667",
      fake1: "fake",
      fake2: "fake2",
      fake3: "fake3",
      fake4: "fake4",
      fake5: "fake5",
      fake6: "fake6",
      fake7: "fake7",
      fake8: "fake8",
      fake9: "fake9",
      fake10: "fake10",
    },
  ];
 
 var dataDetail = {
    1 : detailTableData1,
    2 : detailTableData2,
    3 : detailTableData3,
 }